accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_view

from . import views
from .forms import LoginForm

app_name="accounts"

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(success_url='/'), name='login', kwargs={'authentication_form': LoginForm}),
    url(r'^register/$', views.RegisterView.as_view(success_url="/"), name='register'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout')
]

job/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "job"
urlpatterns = [
    path(r'', views.IndexView.as_view(), name='index'),
    path(r'job/<int:year>/<int:month>/<int:day>/<int:job_id>.html',
         views.JobDetailView.as_view(),
         name='detailbyid'),
    path(r'jobpage/<int:page>/', views.JobListView.as_view(), name='job_page'),
]
if settings.DEBUG:
    # urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

yihang_website/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from yihang_website.admin_site import admin_site

urlpatterns = [
    path('admin/', admin_site.urls),
    url(r'mdeditor/', include('mdeditor.urls')),
    url(r'', include('job.urls', namespace='job')),
    url(r'', include('company.urls', namespace='company')),
    url(r'', include('accounts.urls', namespace='accounts')),
    url(r'^search', include('haystack.urls'), name='search'),
    # url(r'', include('job.urls', namespace='job')),
]

templates/share_layout/base.html
{% load static %}
{% load cache %}
{% load compress %}
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    {% block header %}
    {% endblock %}
    <base href="/">
    <link rel="stylesheet" type="text/css" href="static/css/styles.css"/>
</head>

<body>

<div id="box">
    {% include 'share_layout/header.html' %}

    <div class="content mian">
        {% block joblist %}
        {% endblock %}
    </div>
    {% include 'share_layout/footer.html' %}
</div>


</body>

</html>

templates/share_layout/base_account.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>{{ SITE_NAME }} | {{ SITE_DESCRIPTION }}</title>
    {% load compress %}
    {% compress css %}
        <!-- Bootstrap core CSS -->
        <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'blog/css/oauth_style.css' %}" rel="stylesheet">
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <link href="{% static 'assets/css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">
        <!-- TODC Bootstrap core CSS -->
        <link href="{% static 'assets/css/todc-bootstrap.min.css' %}" rel="stylesheet">
        <!-- Custom styles for this template -->
        <link href="{% static 'assets/css/signin.css' %}" rel="stylesheet">
    {% endcompress %}
    {% compress js %}
        <script src="{% static 'assets/js/ie10-viewport-bug-workaround.js' %}"></script>
        <script src="{% static 'assets/js/ie-emulation-modes-warning.js' %}"></script>
    {% endcompress %}
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
{% block content %}
{% endblock %}

<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->

</body>
</html>

templates/share_layout/footer.html
{% load job_tags %}
{% load cache %}
<div class="footer">
        <div class="line3">
            <div class="lineTop">
                <div class="top1">
                    <a href="" class="hotBtn">友情链接</a>
                </div>
                <div class="btnCon">
                    <a href="">拉勾网</a>
                    <a href="">教师网</a>
                    <a href="">照片</a>
                    <a href="">拉勾网</a>
                    <a href="">教师网</a>
                    <a href="">照片</a>
                    <a href="">拉勾网</a>
                    <a href="">教师网</a>
                    <a href="">照片</a>
                    <a href="">拉勾网</a>
                    <a href="">教师网</a>
                    <a href="">照片</a>
                    <a href="">照片</a>
                    <a href="">拉勾网</a>
                    <a href="">教师网</a>
                    <a href="">照片</a>
                    <a href="">照片</a>
                    <a href="">拉勾网</a>
                    <a href="">教师网</a>
                    <a href="">照片</a>
                    <p class="fr openTxt">展开<img src="../static/img2/open.jpg" alt="" class="fr"/></p>
                </div>
            </div>
        </div>
        <div class="fooTop mian">
            <div class="appBox fl">
                <p class="btnApp"><span></span>下载拉钩APP</p>
                <p class="btnApp"><span></span>微信小程序</p>
                <p class="btnTxt">
                    <img src="../static/img2/icon-wechat.png" alt=""/>拉钩微信
                    <img src="../static/img2/icon-sina1.png" alt=""/>拉钩微博
                </p>
            </div>
            <dl class="fl">
                <dt>企业服务</dt>
                <dd>招聘抢人宝典</dd>
                <dd>公司搜索</dd>
                <dd>拉钩APP</dd>
            </dl>
            <dl class="fl dlCen">
                <dt>企业服务</dt>
                <dd>招聘抢人宝典</dd>
                <dd>公司搜索</dd>
                <dd>拉钩APP</dd>
            </dl>
            <dl class="fl">
                <dt>企业服务</dt>
                <dd>招聘抢人宝典</dd>
                <dd>公司搜索</dd>
                <dd>拉钩APP</dd>
            </dl>
        </div>
        <div class="fooBottom">
            <div class="bottCon mian">
                <p class="txtP1 fl">&copy;2018 拉勾网 京ICP备12312343</p>
                <p class="txtP2 fl"><span class="fl"></span>京公安网备 110108099987658776号</p>
                <div class="txtBox fl">
                    <span class="fl"></span>
                    <p class="fl">
                        违法和不良信息举报<br>
                        电话:4007878<br>
                        邮箱:cc@lagou.com
                    </p>
                </div>
                <div class="fr imgBox"><img src="../static/img/footer_lagou.png" alt=""/></div>
            </div>
        </div>
    </div>

templates/share_layout/header.html
{% load job_tags %}
{% load cache %}
<div class="header">
        <div class="h_top">
            <div class="topCon mian clearFixed">
                <div class="conLeft fl">
                    <div class="leftTxt1 fl">
                        <a href="" class="logo">{{ SITE_NAME }}</a>
                        <a href="" class="city">全国站</a>
                        <a href="" class="city1">[切换城市]</a>
                    </div>
                    <ul class="ulList clearFixed fl">
                        <li><a href="#">首页</a></li>
                        <li><a href="#">公司</a></li>
                        <li><a href="#">校园</a></li>
                        <li><a href="#">言职</a></li>
                        <li><a href="#">课程</a></li>
                    </ul>
                </div>
                <div class="conRight fr">
                    <ul class="ulList clearFixed">
                        {% if user.is_authenticated %}
                            <li><a href="{{ SITE_BASE_URL }}admin/" class="login btn" rel="nofollow">{{ user.username }}   </a>
                            </li>
                            <li><a href="{% url "accounts:logout" %}" class="login2" rel="nofollow"><span>|</span>退出登录</a>
                            </li>
                        {% else %}
                            <li><a href="{% url "accounts:login" %}" class="login btn" rel="nofollow">登录</a>
                        {% endif %}
                        {#                        <li><a href="" class="login btn"><span></span>登录</a></li>#}
                        {#                        <li><a href="" class="login2"><span>|</span>注册</a></li>#}
                        <li><a href="" class="btn app"><span></span>拉钩APP</a></li>
                        <li><a href="demo.html" target="_blank">进入企业版</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="h_bottom">
            <div class="botCon mian">
                <div class="conLeft fl">
                    <div class="imgBox">
                        <img src="../static/img/footer_lagou.png" alt=""/>
                    </div>
                    <div class="txtBox">7555585家公司|67676767个职位在拉钩等你</div>
                </div>
                <div class="conRight fr">
                    <div class="btnBox">
                        <input type="text" placeholder="输入手机号" class="fl txt1"/>
                        <p class="fl pBtn">
                            <input type="text" placeholder="验证码" class="txt2"/>
                            |
                            <a href="" class="aTxt2">获取</a>
                        </p>
                        <input type="submit" value="登录/注册" class="fl btnSub"/>
                    </div>
                </div>
            </div>
        </div>
    </div>

templates/share_layout/search_block.html
{% load job_tags %}
{% load cache %}
<div class="sear">
    <div class="searCon mian">
{#        <div class="search">#}
{#            <input type="text" placeholder="搜索公司,搜索职位或地点" class="searchInp fl"/>#}
{#            <a href="" class="btn fl">搜索</a>#}
{#        </div>#}
        <form role="search" method="get" id="searchform" class="search" action="/search">
            <div>
                <input type="text" value="{{ query }}" name="q" id="q"/>
                <input type="submit" id="searchsubmit" value="搜索"/>
            </div>
        </form>
        <ul class="searList clearFixed">
            <li><a href="">热门搜索 :</a></li>
            <li><a href="">24小时极速入职</a></li>
            <li><a href="">名企校招早班车</a></li>
            <li><a href="">Java面试</a></li>
            <li><a href="">架构设计</a></li>
            <li><a href="">数据分析</a></li>
            <li><a href="">PHP</a></li>
            <li><a href="">C++</a></li>
        </ul>
    </div>
</div>